"""Auxima Activity row builder (CRM §4 invariant + S-25 retention classes).

Every state change in the CRM emits exactly one of these rows. The
Frappe-side ``Auxima Activity`` doctype is the persistent home for
them; this module is the wire-shape contract the sidecar POSTs to
that doctype.

Retention classes (S-25, PDPL §16-§17 + IA Art. 24):

  - ``WORM_AUDIT``  — anchored to S3 Object Lock for 10 years
    (KYC results, bound certificates, signed proposals, claim FNOL).
    Erasure rewrites the payload to a tombstone but preserves the
    skeleton record.
  - ``OPERATIONAL`` — normal MariaDB row; survives PDPL erasure by
    being rewritten with PII redacted but the skeleton kept.
  - ``EPHEMERAL``   — purgeable; not part of the IA audit log
    (e.g. UI hover events, draft auto-saves).

Fields:
  - ``id``              — ULID; lex-sortable so insertion-order =
                          chronological order across the activity stream.
  - ``tenant_id``       — per-tenant scoping; the activity log is
                          per-Frappe-site too, but the field is kept
                          in the wire shape for cross-tenant analytics
                          on the audit replica.
  - ``customer_id``     — optional; some activity rows are tenant-
                          level (e.g. "policy refresh job started")
                          and have no owning customer.
  - ``kind``            — dotted event name (e.g. ``intake.extract.completed``).
  - ``payload``         — redacted JSON-shaped dict. PII patterns are
                          replaced with ``<redacted:*>`` tokens before
                          the row is built so a misconfigured backup
                          can'\''t leak raw PII into a non-WORM bucket.
  - ``retention``       — :class:`RetentionClass`.
  - ``idempotency_key`` — optional; for rows generated by an HTTP
                          endpoint with an Idempotency-Key header.
  - ``source``          — dotted source identifier (e.g.
                          ``"sidecar.intake.extract"`` or
                          ``"frappe.lead.before_save"``) for audit
                          traceability.
  - ``ts``              — timezone-aware UTC datetime.
"""
from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Final, Mapping

from auxima_ai.ids.ulid import MonotonicGenerator, is_valid
from auxima_ai.observability.redact import redact_json

logger = logging.getLogger(__name__)

MAX_KIND_LEN: Final[int] = 128
MAX_TENANT_ID_LEN: Final[int] = 128
MAX_CUSTOMER_ID_LEN: Final[int] = 128
MAX_IDEMPOTENCY_KEY_LEN: Final[int] = 255
MAX_SOURCE_LEN: Final[int] = 128
# Activity payloads are intentionally bounded — anything bigger is a
# document and belongs in S3, not in the activity row.
MAX_PAYLOAD_BYTES: Final[int] = 64 * 1024


class RetentionClass(str, Enum):
    """How long the row must be retained and how erasure is handled."""

    WORM_AUDIT = "worm_audit"
    OPERATIONAL = "operational"
    EPHEMERAL = "ephemeral"


# ---------------------------------------------------------------------------
# Errors
# ---------------------------------------------------------------------------


class ActivityRowError(ValueError):
    """Base — every validation failure raises a subclass of this."""


class InvalidActivityFieldError(ActivityRowError):
    """Raised when an ActivityRow field is malformed."""


class PayloadTooLargeError(ActivityRowError):
    """Raised when the JSON-encoded payload exceeds MAX_PAYLOAD_BYTES."""


# ---------------------------------------------------------------------------
# Value object
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class ActivityRow:
    """One row of the Auxima Activity log."""

    id: str
    tenant_id: str
    kind: str
    payload: Mapping[str, Any]
    retention: RetentionClass
    source: str
    ts: datetime
    customer_id: str | None = None
    idempotency_key: str | None = None
    redaction_applied: bool = False

    def __post_init__(self) -> None:
        _check_ulid("id", self.id)
        _check_nonempty_str("tenant_id", self.tenant_id, MAX_TENANT_ID_LEN)
        _check_dotted_lowercase("kind", self.kind, MAX_KIND_LEN)
        _check_payload(self.payload)
        if not isinstance(self.retention, RetentionClass):
            raise InvalidActivityFieldError(
                f"retention must be RetentionClass; got {type(self.retention).__name__}"
            )
        _check_nonempty_str("source", self.source, MAX_SOURCE_LEN)
        _check_utc_datetime("ts", self.ts)
        if self.customer_id is not None:
            _check_nonempty_str("customer_id", self.customer_id, MAX_CUSTOMER_ID_LEN)
        if self.idempotency_key is not None:
            _check_nonempty_str(
                "idempotency_key", self.idempotency_key, MAX_IDEMPOTENCY_KEY_LEN,
            )
        if not isinstance(self.redaction_applied, bool):
            raise InvalidActivityFieldError(
                "redaction_applied must be bool; got "
                f"{type(self.redaction_applied).__name__}"
            )


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


def _check_ulid(name: str, value: str) -> None:
    if not is_valid(value):
        raise InvalidActivityFieldError(f"{name} must be a valid ULID; got {value!r}")


def _check_nonempty_str(name: str, value: object, max_len: int) -> None:
    if not isinstance(value, str) or not value:
        raise InvalidActivityFieldError(f"{name} must be a non-empty string")
    if len(value) > max_len:
        raise InvalidActivityFieldError(
            f"{name} length {len(value)} exceeds maximum {max_len}"
        )


def _check_dotted_lowercase(name: str, value: object, max_len: int) -> None:
    """Dotted lowercase + digits + underscore + hyphen; not empty.

    Stricter than the log-event name in observability.log: activity
    kinds are persisted to the audit log, so lowercase-only avoids the
    "intake.Extract" / "intake.extract" duplicate-key class of bug.
    """
    if not isinstance(value, str) or not value:
        raise InvalidActivityFieldError(f"{name} must be a non-empty string")
    if len(value) > max_len:
        raise InvalidActivityFieldError(
            f"{name} length {len(value)} exceeds maximum {max_len}"
        )
    for ch in value:
        if ch.isupper():
            raise InvalidActivityFieldError(
                f"{name} must be lowercase; got {value!r}"
            )
        if not (ch.isalnum() or ch in "._-"):
            raise InvalidActivityFieldError(
                f"{name} must contain only [a-z0-9._-]; got {value!r}"
            )


def _check_payload(payload: object) -> None:
    if not isinstance(payload, Mapping):
        raise InvalidActivityFieldError(
            f"payload must be a Mapping; got {type(payload).__name__}"
        )
    # Estimate JSON size — use repr-ish length so we don't import json
    # twice. The conservative path is the right side of the boundary.
    import json as _json
    try:
        encoded = _json.dumps(dict(payload), default=str)
    except (TypeError, ValueError) as e:
        raise InvalidActivityFieldError(
            f"payload must be JSON-serialisable; got {e}"
        ) from e
    if len(encoded.encode("utf-8")) > MAX_PAYLOAD_BYTES:
        raise PayloadTooLargeError(
            f"payload exceeds {MAX_PAYLOAD_BYTES} bytes; store large "
            "artefacts in object storage and reference them by URL"
        )


def _check_utc_datetime(name: str, value: object) -> None:
    if not isinstance(value, datetime):
        raise InvalidActivityFieldError(
            f"{name} must be datetime; got {type(value).__name__}"
        )
    if value.tzinfo is None or value.tzinfo.utcoffset(value) is None:
        raise InvalidActivityFieldError(
            f"{name} must be timezone-aware (UTC strongly recommended); "
            "naive datetimes invite double-counting at boundaries"
        )


# ---------------------------------------------------------------------------
# Builder
# ---------------------------------------------------------------------------


_ids: Final[MonotonicGenerator] = MonotonicGenerator()


def build_activity_row(
    *,
    tenant_id: str,
    kind: str,
    payload: Mapping[str, Any],
    retention: RetentionClass,
    source: str,
    customer_id: str | None = None,
    idempotency_key: str | None = None,
    ts: datetime | None = None,
    row_id: str | None = None,
) -> ActivityRow:
    """Build an :class:`ActivityRow`, redacting PII from the payload.

    The redactor (:func:`auxima_ai.observability.redact.redact_json`)
    runs over the payload before construction so a misconfigured
    backup or replica can'\''t leak raw PII into a non-WORM bucket.
    The ``redaction_applied`` flag tells downstream code whether the
    redactor fired — useful for "we saw PII here" telemetry without
    needing to re-scan the row.

    Defaults:
      - ``ts`` → :func:`datetime.now(timezone.utc)`
      - ``row_id`` → fresh monotonic ULID from the package-level generator
    """
    # Validate payload shape BEFORE redaction. redact_json walks dicts
    # recursively, so a non-mapping payload (str/list/int) would either
    # silently pass through (str) or crash deep in the redactor. A
    # cyclic dict would recurse forever. Validate the boundary first.
    _check_payload(payload)
    payload_dict = dict(payload) if payload else {}
    redacted_payload, fired = redact_json(payload_dict)
    return ActivityRow(
        id=row_id if row_id is not None else _ids.generate(),
        tenant_id=tenant_id,
        kind=kind,
        payload=redacted_payload,
        retention=retention,
        source=source,
        ts=ts if ts is not None else datetime.now(timezone.utc),
        customer_id=customer_id,
        idempotency_key=idempotency_key,
        redaction_applied=bool(fired),
    )


__all__ = (
    "ActivityRow",
    "ActivityRowError",
    "InvalidActivityFieldError",
    "MAX_CUSTOMER_ID_LEN",
    "MAX_IDEMPOTENCY_KEY_LEN",
    "MAX_KIND_LEN",
    "MAX_PAYLOAD_BYTES",
    "MAX_SOURCE_LEN",
    "MAX_TENANT_ID_LEN",
    "PayloadTooLargeError",
    "RetentionClass",
    "build_activity_row",
)
